bvaughn/react-error-boundary

package.json, src/ErrorBoundary.js
`componentDidCatch` is supported by React16, so we should remove `unstable_handleError`.
=> Remove unstable_handleError

package.json, src/ErrorBoundary.js, src/index.js
This serves the use case outlined in this issue: https://github.com/bvaughn/react-error-boundary/issues/4
@bvaughn How about adding React flow types to make the typing on the function a bit tighter than *?
=> withErrorBoundary decorator function.

package.json
So npm page will have a link to the repo: https://www.npmjs.com/package/react-error-boundary
=> Add repository and hompage fields to package.json

.babelrc, jest.config.js, package.json, src/ErrorBoundary.js, src/ErrorBoundary.test.js, src/ErrorBoundaryFallbackComponent.test.js, src/__snapshots__/ErrorBoundaryFallbackComponent.test.js.snap, src/setupTests.js, yarn.lock
I’ve added the following test cases…
* ErrorBoundary
* Renders the child component if there is no error
* Sets its state to an error state and renders the default fallback component
* Sets its state to an error state and renders a custom fallback component
* Sets its state to an error state and invokes the onError callback prop
* ErrorBoundaryFallbackComponent
* Passes a snapshot test
I had to add `// istanbul ignore next` comments for two lines; couldn’t reproduce the scenario in test environment. Otherwise, we have 100% test coverage. 🎉
Side note: I also have some other improvements to suggest in the `withErrorBoundary` higher-order component. I’ll send pull requests for them separately.
Fixes #7.
=> Add Jest tests

README.md
**What**: It looks like with version 2, `ErrorBoundary` has changed to a named export. The docs show 
```javascript
import ErrorBoundary from 'react-error-boundary'
```
when it should be
```javascript
import { ErrorBoundary } from 'react-error-boundary'
```
**Why**: The current documentation is incorrect, so those upgrading will receive any error.
**How**: Just a simple documentation update.
**Checklist**:
=> Update README to used named export for ErrorBoundary

README.md, index.d.ts, src/__tests__/index.js, src/index.js
**What**: add onReset and resetKeys props
**Why**: This makes error recovery much easier (and more declarative)
**How**: make onReset be called before resetting the internal state and compare resetKeys between renders
**Checklist**:
=> feat(reset): add onReset and resetKeys props

README.md, src/__tests__/index.js, src/index.js
**What**: pass arguments to onReset callback
Whatever is passed to `resetErrorBoundary` will be forwarded along to `onReset`. In the case of `resetKeys` it'll be passed the previous resetKeys and the current `resetKeys`.
**Why**:
This will allow users to differentiate what triggered the reset so they
know how to proceed with their recovery.
**How**:
1. Take the args in `resetErrorBoundary` and forward them to the `onReset` call.
2. Pass the `prevProps.resetKeys` and `this.props.resetKeys` to `resetErrorBoundary`
Not sure how to type this with TypeScript so I'll wait for someone to fix that up later.
**Checklist**:
=> feat(onReset): pass arguments to onReset callback

README.md, index.d.ts, src/__tests__/index.js, src/index.js
**What**: add the `onResetKeysChange` prop which is a function to handle when the reset keys change.
**Why**: This makes it easier to handle when the reset occurred due to a change in the resetKeys vs a call to `resetErrorBoundary`
**How**: Remove the call of `resetErrorBoundary` from `componentDidUpdate` and instead call `setState` directly and call the `onResetKeysChange` if it's provided
**Checklist**:
=> feat(onResetKeysChange): a function to handle when the reset keys change

src/__tests__/index.js, src/index.js
**What**:
When determining whether to reset state/call `onResetKeysChange` callback, also checks if the length of the `resetKeys` dependency array changes.
**Why**:
Edge case where `resetKeys` array is computed dynamically and its length could change.
**How**:
Added a length comparison check to `changedArray`.
**Checklist**:
=> Compare length of resetKeys when checking if resetKeys has changed

package.json
**What**:
I do get an eslint error `FallbackProps not found in 'react-error-boundary'  import/named` with `eslint-import-resolver-typescript` as it seems that the built js bundles gets favored over the included types. 
**Why**:
I'm aware that the problem might be related to how `eslint-import-resolver-typescript` is trying to resolve the types, but adding the the `types` prop in package.json fixes the issue and is advised by the typescript team anyways. 
**How**:
point the `types` prop in package.json to the declaration file.
**Checklist**:
=> point package.json types property to including type declarations

README.md, index.d.ts, src/__tests__/hook.js, src/__tests__/index.js, src/index.js
**What**: feat(useErrorHandler): add new hook for handling errors
**Why**: to make it easier to handle the errors that React doesn't automatically propagate to ErrorBoundaries
**How**:
- Add two tests
- Implement
- Document
**Checklist**:
=> feat(useErrorHandler): add new hook for handling errors

package.json, src/__tests__/index.js, src/index.js
fix #61 
**What**: React Component can be function but also objects. To check if a component is a real one I have used `react-is` 
**Why**: Because with `styled-components` the `ErrorBoundary` threw an error
**How**: using a library from Facebook `react-is`
**Checklist**:
=> fix: FallbackComponent type

README.md, src/__tests__/index.js, src/index.js
**What**: fix: avoid double-render
**Why**: Closes #66 and Closes #67
**How**:
- Remove the `setState` call in `componentDidCatch`
- Ensure that the cDU only resets if the component is updated *after* the first update with an error.
**Checklist**:
BREAKING CHANGE: This removes the `componentStack` in the props given to the `FallbackComponent` and `fallbackRender`
=> fix: avoid double-render

index.d.ts
**What**:
Updates the `index.d.ts` file to match the changes made in [the v3 release](https://github.com/bvaughn/react-error-boundary/releases/tag/v3.0.0):
>  This removes the `componentStack` in the props given to the `FallbackComponent` and `fallbackRender`
**Why**:
Because the types in `index.d.ts` were incompatible with the new v3 API, resulting in unsafe typings.
**How**:
Removes the `componentStack` property from the `FallbackProps` type.
**Checklist**:
=> Update TS Types for v3 Breaking Change

index.d.ts
**What**:
Update the type definitions to match the data passed to onError.
**Why**:
onError is passed the whole "info" object from componentDidCatch and not just the componentStack. The README has the correct types in an example, but the type definitions are incorrect.
**How**:
**Checklist**:
=> Fix TypeScript types for onError

src/__tests__/hook.tsx, src/__tests__/index.tsx, src/index.tsx
**What**:
- Fix ignored update via `resetKeys` after `ErrorBoundary` error state is triggered on component mount. 
- Add test for this case.
- I also needed to update a couple of snapshots to make it. That was strange to me.
**Why**:
Closes #74 and Closes #84
**How**:
Adding extra check of `this.updatedWithError` on `componentDidMount`
**Checklist**:
- Documentation N/A
=> fix: ignored update after error triggered on component mount 

src/__tests__/hook.tsx, src/__tests__/index.tsx, src/index.tsx
…nion
This fixes a lot of issue concerning the union and ensures typescript which is which
**What**: Assist typescript in union type of `ErrorBoundaryProps` and cleanup related leftovers
**Why**: A linting error was present on master
**How**: NA
**Checklist**:
- [X ] Ready to be merged
Snapshots needed updating because of the stacktrace changes
=> fix(TS): help typescript to find his way for the ErrorBoundaryProps

README.md, src/index.tsx
In the useErrorHandler hook, i've changed the type of the error from `Error` to `unknown`.
**What**:
Not all thrown exceptions are of type `Error`, see #83 for a discussion concerning this change
**Why**:
NA
**How**:
I've made the changes as agreed upon and also corrected the documentation
**Checklist**:
I've noticed that current master has a linting issue on the fallback in the render method, i'll take a look at it
=> useErrorHandler: use unknown instead of Error

README.md, src/index.ts
**What**:
Improve error message when used in React Server Components
**Why**:
Current message just states "TypeError: Class extends value undefined is not a constructor or null" which isn't helpful to the developer.
Now we can use `<ErrorBoundary fallback={<div>Bad</div>} />` without issues on the server and get a helpful message when using props that we can't serialize:
`<ErrorBoundary fallbackRender={() =>{}} />` produces 
```
Error: Functions cannot be passed directly to Client Components because they're not serializable.
<... fallbackRender={function} children=...>
^^^^^^^^^^
```
**How**:
Add `'use client';` directive
**Checklist**:
- ~[ ]~ Tests
=> feat: Improve error message when used in React Server Components

package.json
The 4.0.0 release commit removed the entry to set side effects to false. As far as I can tell this release didn't introduce any side effects, was this by accident?
Link to code diff: https://github.com/bvaughn/react-error-boundary/commit/9a91190e697084800bb93cd42c554118d13aa527#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L9
I can't see any side-effectful code from a quick inspection, so it seems safe to re-add this.
=> Re-add sideEffects false to package.json

src/ErrorBoundary.ts
**What**:
1. ErrorBoundary Component init state in constructor
2. resetErrorBoundary: not use arrow func to bind this
**Why**:
in old safari  version  it will case [Unexpected token '='. Expected an opening '(' before a method's parameter list](https://stackoverflow.com/questions/60026651/safari-unexpected-token-expected-an-opening-before-a-methods-paramet) error.
the npm dist code is such as,  but some browser not support arrow function.
```js
class $6d6d4999e62b3ee0$export$e926676385687eaf extends (0, $8zHUo$react.Component) {
state = $6d6d4999e62b3ee0$var$initialState;
static getDerivedStateFromError(error) {
return {
didCatch: true,
error: error
};
}
resetErrorBoundary = (...args)=>{
const { error: error  } = this.state;
if (error !== null) {
this.props.onReset?.({
args: args,
reason: …
```
=> fix: error boundary use arrow fun case parameter list error

README.md, src/ErrorBoundary.ts
closes #145
**What**:
- Remove type casting in ErrorBoundary.prototype.render
- ~~Remove outdated warning in README~~
**Why**:
For whatever reason (I didn't want to invest much time into debugging React types), `ReactElement` returned from class component render function is not compatible with JSX declarations.
My change is removing the explicit type, which makes it fall back to the inferred type
```ts
ErrorBoundary.render(): React.FunctionComponentElement<React.ProviderProps<ErrorBoundaryContextType | null>>
```
I've seen this commit 63339c36f7ff6e16a9648f4d0afea085cb69bb2a, which added `as ReactElement` in the first place. However, after short investigation, I noticed that the distributed files don't suffer from the original problem of broken import paths. So I assumed it is safe to …
=> fix: remove ReactElement casting from render

babel.config.js, package.json, pnpm-lock.yaml
**What**: Added `@babel/preset-env` as a `devDependency`
**Why**: To support older browsers (e.g. Safari 12)
**How**: Added `@babel/preset-env` as a `devDependency`
**Checklist**:
I'm not sure why this was not a default setup. If it was a deliberate choice feel free to decline this PR.
=> Added @babel/preset-env to ensure compatibility with older browsers

src/types.ts
**What**: fix ErrorBoundarySharedProps's info type
**Why**: ErrorBoundarySharedProps's info can follow ErrorInfo of react
**How**: connect ErrorBoundary.onError.info to React.ErrorInfo
**Checklist**:
=> fix: ErrorBoundarySharedProps's info type

.github/workflows/jest.yml, .github/workflows/prettier.yml, .github/workflows/typescript.yml
**What**: .nvmrc as source of actions/setup-node@v3's following version
**Why**: actions/setup-node@v3 will use just latest node-version. but this project use exact node version, as written in .nvmrc
**How**: use actions/setup-node@v3's option node-version-file
**Checklist**:
=> chore: use .nvmrc as source of actions/setup-node@v3's following version

src/ErrorBoundary.ts
**What**:
Per the conversation in https://github.com/bvaughn/react-error-boundary/issues/159, it would be great if we propagated the original error, when no type of fallback is provided. This PR addresses that.
> Additionally I opted to log a `console.error` to guide the developer in understanding the issue. Unsure if this affects react server components in any way. 
**How**:
Just threw the original error back.
> The one **potential** breaking change here is that there's no longer an expectation that this component throws an `Error` type as the error itself could be anything.
**Checklist**:
=> fix: propagate original error

src/useErrorBoundary.ts
**What**: I type-narrowed useErrorBoundary's state
**Why**: I want to express state type clearly
**How**: described in below code
```ts
type UseErrorBoundaryState = {
error: Error | null;
hasError: boolean;
};
```
```ts
type UseErrorBoundaryState<Error> =
| { error: Error; hasError: true }
| { error: null; hasError: false };
```
**Checklist**:
=> fix(useErrorBoundary): state type narrow

package.json
**What**: Change package.json's scripts
**Why**: The use of "npm" in projects using the "pnpm" package manager is awkward and confusing.
**How**: Replace "npm run" with "pnpm"
**Checklist**:
=> change the script from npm to pnpm

package.json, pnpm-lock.yaml
**What**:
* add rimraf library
**Why**:
* contributors and users of open-source projects work in different environments, including Windows, macOS, and Linux.
* since rm -rf doesn’t work natively on Windows, contributors on that platform would encounter issues unless they install tools like Git Bash or WSL.
**How**:
* if we use rimraf, it can ensure accessibility and compatibility for everyone.
**Checklist**:
=> chore(package.json): add rimraf

src/types.ts
**What**:
* remove unnecessay declare function FallbackRender
**Why**:
* declare is only necessary for external modules or global scope.
* using declare for internally used functions or types is unnecessary.
* if the function is not provided externally, it is clearer to define it explicitly.
* improved code consistency and readability.
* by removing unnecessary declare keywords, the code becomes more concise and maintains a consistent structure.
* directly defining function types reduces confusion between implementation and declaration.
**How**:
* ensuring consistency between types and implementation.
* by removing declare and managing type definitions alongside implementations, it prevents inconsistencies between types and actual behavior.
* code changes ensure that type definitions and …
=> refactor(types.ts): remove unnecessary declare function FallbackRender

.github/workflows/ci.yml
**What**:
* removed the `version` specified in the `with` field of `pnpm/action-setup`.
**Why**:
* [pnpm/action-setup automatically recognizes the pnpm version defined in the packageManager field of package.json](https://github.com/pnpm/action-setup/tree/v4/?tab=readme-ov-file#version). specifying the version in the with field is redundant, adds unnecessary complexity, and increases maintenance overhead. relying on the `packageManager` field ensures simplicity and consistency.
**How**:
* removed the version field from the with configuration in `.github/workflows/ci.yml`. the pnpm version will now be derived directly from the `packageManager` field in `package.json`.
**Checklist**:
=> chore(.github/workflows/ci.yml): remove version field in with of pnpm/action-setup
